"""create phase zero durable contracts

Revision ID: 7a4cb7f003f4
Revises: 
Create Date: 2026-09-01 20:16:04.673706
"""
from alembic import op
import sqlalchemy as sa

revision = '7a4cb7f003f4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analysis_task',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.String(length=200), nullable=False),
    sa.Column('user_id', sa.String(length=200), nullable=False),
    sa.Column('domain_id', sa.String(length=200), nullable=False),
    sa.Column('business_question', sa.Text(), nullable=False),
    sa.Column('state', sa.String(length=40), nullable=False),
    sa.Column('parent_task_id', sa.UUID(), nullable=True),
    sa.Column('context_version', sa.String(length=100), nullable=True),
    sa.Column('semantic_package_version', sa.String(length=100), nullable=True),
    sa.Column('dataset_snapshot_id', sa.String(length=200), nullable=True),
    sa.Column('idempotency_key', sa.String(length=200), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_task_id'], ['analysis_task.id'], ),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_analysis_task'))
    )
    op.create_index(op.f('ix_analysis_task_state'), 'analysis_task', ['state'], unique=False)
    op.create_index(op.f('ix_analysis_task_tenant_id'), 'analysis_task', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_analysis_task_user_id'), 'analysis_task', ['user_id'], unique=False)
    op.create_table('evaluation_case',
    sa.Column('case_id', sa.String(length=20), nullable=False),
    sa.Column('suite_version', sa.String(length=100), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('case_id', name=op.f('pk_evaluation_case'))
    )
    op.create_table('evaluation_run',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('suite_version', sa.String(length=100), nullable=False),
    sa.Column('model_provider_version', sa.String(length=200), nullable=False),
    sa.Column('payload', sa.JSON(), server_default='{}', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_evaluation_run'))
    )
    op.create_table('analysis_context',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('context_version', sa.String(length=100), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['analysis_task.id'], ),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_analysis_context'))
    )
    op.create_index(op.f('ix_analysis_context_task_id'), 'analysis_context', ['task_id'], unique=False)
    op.create_table('analysis_plan',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('context_version', sa.String(length=100), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['analysis_task.id'], ),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_analysis_plan'))
    )
    op.create_index(op.f('ix_analysis_plan_task_id'), 'analysis_plan', ['task_id'], unique=False)
    op.create_table('artifact',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('artifact_type', sa.String(length=50), nullable=False),
    sa.Column('content_hash', sa.String(length=128), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['analysis_task.id'], ),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_artifact'))
    )
    op.create_index(op.f('ix_artifact_task_id'), 'artifact', ['task_id'], unique=False)
    op.create_table('audit_event',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=True),
    sa.Column('actor_id', sa.String(length=200), nullable=False),
    sa.Column('action', sa.String(length=200), nullable=False),
    sa.Column('outcome', sa.String(length=40), nullable=False),
    sa.Column('payload', sa.JSON(), server_default='{}', nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['analysis_task.id'], ),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_event'))
    )
    op.create_index(op.f('ix_audit_event_task_id'), 'audit_event', ['task_id'], unique=False)
    op.create_table('claim',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('claim_type', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['analysis_task.id'], ),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_claim'))
    )
    op.create_index(op.f('ix_claim_task_id'), 'claim', ['task_id'], unique=False)
    op.create_table('domain_event',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=80), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['analysis_task.id'], ),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_domain_event'))
    )
    op.create_index(op.f('ix_domain_event_task_id'), 'domain_event', ['task_id'], unique=False)
    op.create_table('evaluation_result',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('evaluation_run_id', sa.UUID(), nullable=False),
    sa.Column('case_id', sa.String(length=20), nullable=False),
    sa.Column('passed', sa.String(length=10), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['evaluation_case.case_id'], ),
    sa.ForeignKeyConstraint(['evaluation_run_id'], ['evaluation_run.id'], ),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_evaluation_result'))
    )
    op.create_index(op.f('ix_evaluation_result_evaluation_run_id'), 'evaluation_result', ['evaluation_run_id'], unique=False)
    op.create_table('execution_record',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('tool_name', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('result_hash', sa.String(length=128), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['analysis_task.id'], ),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_execution_record'))
    )
    op.create_index(op.f('ix_execution_record_task_id'), 'execution_record', ['task_id'], unique=False)
    op.create_table('hypothesis',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('state', sa.String(length=40), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['analysis_task.id'], ),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_hypothesis'))
    )
    op.create_index(op.f('ix_hypothesis_task_id'), 'hypothesis', ['task_id'], unique=False)
    op.create_table('runtime_checkpoint',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('state_version', sa.Integer(), nullable=False),
    sa.Column('storage_uri', sa.Text(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['analysis_task.id'], ),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_runtime_checkpoint'))
    )
    op.create_index(op.f('ix_runtime_checkpoint_task_id'), 'runtime_checkpoint', ['task_id'], unique=False)
    op.create_table('task_state',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('from_state', sa.String(length=40), nullable=True),
    sa.Column('to_state', sa.String(length=40), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('payload', sa.JSON(), server_default='{}', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['analysis_task.id'], ),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_task_state'))
    )
    op.create_index(op.f('ix_task_state_task_id'), 'task_state', ['task_id'], unique=False)
    op.create_table('validation_result',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('rule_id', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['analysis_task.id'], ),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_validation_result'))
    )
    op.create_index(op.f('ix_validation_result_task_id'), 'validation_result', ['task_id'], unique=False)
    op.create_table('analysis_step',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('plan_id', sa.UUID(), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['analysis_plan.id'], ),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_analysis_step'))
    )
    op.create_index(op.f('ix_analysis_step_plan_id'), 'analysis_step', ['plan_id'], unique=False)
    op.create_table('context_source_ref',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('context_id', sa.UUID(), nullable=False),
    sa.Column('source_type', sa.String(length=80), nullable=False),
    sa.Column('identifier', sa.String(length=300), nullable=False),
    sa.Column('version', sa.String(length=100), nullable=False),
    sa.Column('content_hash', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['context_id'], ['analysis_context.id'], ),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_context_source_ref'))
    )
    op.create_index(op.f('ix_context_source_ref_context_id'), 'context_source_ref', ['context_id'], unique=False)
    op.create_table('observation',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('execution_id', sa.UUID(), nullable=False),
    sa.Column('result_hash', sa.String(length=128), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['execution_id'], ['execution_record.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['analysis_task.id'], ),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_observation'))
    )
    op.create_index(op.f('ix_observation_task_id'), 'observation', ['task_id'], unique=False)
    op.create_table('semantic_asset_ref',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('context_id', sa.UUID(), nullable=False),
    sa.Column('asset_type', sa.String(length=80), nullable=False),
    sa.Column('asset_id', sa.String(length=300), nullable=False),
    sa.Column('version', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['context_id'], ['analysis_context.id'], ),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_semantic_asset_ref'))
    )
    op.create_index(op.f('ix_semantic_asset_ref_context_id'), 'semantic_asset_ref', ['context_id'], unique=False)
    op.create_table('evidence',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('observation_id', sa.UUID(), nullable=False),
    sa.Column('execution_id', sa.UUID(), nullable=False),
    sa.Column('result_hash', sa.String(length=128), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['execution_id'], ['execution_record.id'], ),
    sa.ForeignKeyConstraint(['observation_id'], ['observation.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['analysis_task.id'], ),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_evidence'))
    )
    op.create_index(op.f('ix_evidence_task_id'), 'evidence', ['task_id'], unique=False)
    op.create_table('claim_evidence_link',
    sa.Column('claim_id', sa.UUID(), nullable=False),
    sa.Column('evidence_id', sa.UUID(), nullable=False),
    sa.Column('relation', sa.String(length=40), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['claim_id'], ['claim.id'], ),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidence.id'], ),
    sa.PrimaryKeyConstraint('claim_id', 'evidence_id', name=op.f('pk_claim_evidence_link'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('claim_evidence_link')
    op.drop_index(op.f('ix_evidence_task_id'), table_name='evidence')
    op.drop_table('evidence')
    op.drop_index(op.f('ix_semantic_asset_ref_context_id'), table_name='semantic_asset_ref')
    op.drop_table('semantic_asset_ref')
    op.drop_index(op.f('ix_observation_task_id'), table_name='observation')
    op.drop_table('observation')
    op.drop_index(op.f('ix_context_source_ref_context_id'), table_name='context_source_ref')
    op.drop_table('context_source_ref')
    op.drop_index(op.f('ix_analysis_step_plan_id'), table_name='analysis_step')
    op.drop_table('analysis_step')
    op.drop_index(op.f('ix_validation_result_task_id'), table_name='validation_result')
    op.drop_table('validation_result')
    op.drop_index(op.f('ix_task_state_task_id'), table_name='task_state')
    op.drop_table('task_state')
    op.drop_index(op.f('ix_runtime_checkpoint_task_id'), table_name='runtime_checkpoint')
    op.drop_table('runtime_checkpoint')
    op.drop_index(op.f('ix_hypothesis_task_id'), table_name='hypothesis')
    op.drop_table('hypothesis')
    op.drop_index(op.f('ix_execution_record_task_id'), table_name='execution_record')
    op.drop_table('execution_record')
    op.drop_index(op.f('ix_evaluation_result_evaluation_run_id'), table_name='evaluation_result')
    op.drop_table('evaluation_result')
    op.drop_index(op.f('ix_domain_event_task_id'), table_name='domain_event')
    op.drop_table('domain_event')
    op.drop_index(op.f('ix_claim_task_id'), table_name='claim')
    op.drop_table('claim')
    op.drop_index(op.f('ix_audit_event_task_id'), table_name='audit_event')
    op.drop_table('audit_event')
    op.drop_index(op.f('ix_artifact_task_id'), table_name='artifact')
    op.drop_table('artifact')
    op.drop_index(op.f('ix_analysis_plan_task_id'), table_name='analysis_plan')
    op.drop_table('analysis_plan')
    op.drop_index(op.f('ix_analysis_context_task_id'), table_name='analysis_context')
    op.drop_table('analysis_context')
    op.drop_table('evaluation_run')
    op.drop_table('evaluation_case')
    op.drop_index(op.f('ix_analysis_task_user_id'), table_name='analysis_task')
    op.drop_index(op.f('ix_analysis_task_tenant_id'), table_name='analysis_task')
    op.drop_index(op.f('ix_analysis_task_state'), table_name='analysis_task')
    op.drop_table('analysis_task')
    # ### end Alembic commands ###
